export default {
    lead: {
        Person: ' Person',
        Organization: ' Organization',
        Email: 'Email',
        Company: 'Company',
        Mobile: 'Mobile',
        Website: 'Website',
        Budget: 'Budget',
        Notes: 'Notes',
        Description: 'Description',
        Level: 'Level',
        Currency: 'Currency',
        Tag: 'Tag',
    },
    deal: {
        Email: 'Email',
        Company: 'Company',
        Mobile: 'Mobile',
        Website: 'Website',
        other: 'Other',
        Notes: 'Notes',
        Street: 'Street',
        Street2: 'Street2',
        Country: 'Country',
        Currency: 'Currency',
        City: 'City',
        State: 'State',
        Postal: 'Postal Code',
    },
    invoice: {
        Email: 'Email',
        Company: 'Company',
        Mobile: 'Mobile',
        Website: 'Website',
        Other: 'Other',
        Notes: 'Notes',
        Street: 'Street',
        // Street2: 'Street2',
        // Country: 'Country',
        Currency: 'Currency',
        // City: 'City',
        // State: 'State',
        // Postal: 'Postal Code',

    },
    estimate: {
        Email: 'Email',
        Company: 'Company',
        Mobile: 'Mobile',
        Website: 'Website',
        Other: 'Other',
        Notes: 'Notes',
        Street: 'Street',
        // Street2: 'Street2',
        // Country: 'Country',
        // Currency: 'Currency',
        // City: 'City',
        State: 'State',
        Postal: 'Postal Code',

    },
    project: {
        Title: 'Title',
        Person: ' Person',
        Organization: ' Organization',
        Email: 'Email',
        Company: 'Company',
        Mobile: 'Mobile',
        Budget: 'Budget',
        Other: 'Other',
        Status: 'Status',
        Currency: 'Currency',
        Tag: 'Tag',
        Description: 'Description',
        Notes: 'Notes',
    },
    organization: {
        Email: 'Email',
        Company: 'Company',
        Mobile: 'Mobile',
        Website: 'Website',
        Address: 'Address',
        Region: 'Region',
        Description: 'Description',
        Country: 'Country',
        Currency: 'Currency',
        City: 'City',
        State: 'State',
        Postal: 'Postal Code',

    },
    person: {
        Email: 'Email',
        Company: 'Company',
        Mobile: 'Mobile',
        Website: 'Website',
        Address: 'Address',
        Region: 'Region',
        Description: 'Description',
        Country: 'Country',
        Currency: 'Currency',
        City: 'City',
        State: 'State',
        Postal: 'Postal Code',

    }

}

